Adding a case for multi-line block style expressions
poached/styleguides pull request #1
Opened 2017-04-17 18:09 UTC by callovarne

I don't thing the DockYard handlebars rules work well for multi-line block stye expressions; what do you think of this?

2017-04-17 18:45 UTC, rafaelbnp requested changes

2017-04-17 18:45 UTC, rafael-paiva commented on engineering/handlebars.md
> +{{/x-thing}}
Agree. I don't like that other indentation as well 👍 
To be honest maybe it was my confusion, I was doing that for multi-line *block* expressions and not for the "not block"(?) ones. Should we really indent 4 spaces in this last case? I don't think I've seen we using that indentation. Maybe we can adjust that here as well?

2017-04-18 00:20 UTC, callovarne commented on engineering/handlebars.md
> +{{/x-thing}}
Also agree. Updated.

2017-04-18 01:24 UTC, rafaelbnp approved these changes
👍

2017-09-20 22:04 UTC, rafael-paiva commented
@jcowley I think we forgot to merge this PR.

2017-09-20 22:56 UTC, merged