Remove 'declare variables at top' rule
poached/styleguides pull request #4
Opened 2018-07-20 22:26 UTC by jcowley

Propose that we remove the guideline that suggests declaring variables at the top as it is outdated and reduces readability for longer, more complex functions.

References for discussion:

- [StackOverflow discussion on the topic](https://stackoverflow.com/questions/5053073/is-defining-every-variable-at-the-top-always-the-best-approach)
  - In particular, I find the example in the top-voted answer about the separation of when variables are declared and used to be the thing I'm struggling with. Declaring a variable 20 lines before it's used (vs right before the few lines of code that use it) makes the code harder to read
- [Medium article on the topic](https://medium.com/@bluepnume/theres-no-need-to-define-all-javascript-vars-once-at-the-top-of-a-function-and-there-hasn-t-been-a66b31f21822)

In searching around, it seems that a majority people find putting variables at the top to be a bad practice.

2018-07-21 00:06 UTC, callovarne commented
Thanks for linking the discussion. Let's give it a try! There was a note in the discussion about the importance of using a linter to catch the occasional issue. The UI has ESLint; what do you think about adding it to the API project?

2018-07-21 00:10 UTC, mossymaker requested changes
Would it be better to replace the rule with a recommendation on where to declare variables, e.g. [Airbnb: JavaScript Style Guide](https://github.com/airbnb/javascript#variables--define-where-used)?
> Assign variables where you need them, but place them in a reasonable place.
>>Why? let and const are block scoped and not function scoped.

We may want to provide rationale with each recommendation going forward; I think that would make it easier to reason about updates as JavaScript evolves.

2018-07-24 19:21 UTC, rafael-paiva commented
Good discussion here! I like the proposal, to me it makes perfectly sense to remove this rule. I also agree with Patrick to replace it with a recommendation. Good resources!

2018-07-25 12:40 UTC, jcowley commented
Updated. I like the Airbnb style guide, in particular because it does provide rationale for most rules.

Regarding adding a linter to the API project... I think it would be helpful to have one, but I worry that retroactively applying a set of rules to an existing code base would require significant refactoring, debugging, and QA, plus the added risk of introducing bugs into production. I doubt the return on that investment would justify the cost, especially since we're moving toward serverless.

2018-07-25 13:30 UTC, rafaelbnp approved these changes

2018-09-12 17:43 UTC, rafael-paiva commented
@jcowley should we merge this?

2018-09-12 17:44 UTC, merged